use std::collections::{BTreeMap, BTreeSet, VecDeque};
use std::fmt::Write as _;
use std::io::Write as _;
use std::path::Path;
use std::process::{Command, Stdio};

use serde_json::{Map, Value};

const HEADER: &str = "// Code generated by `cargo xtask generate`. DO NOT EDIT.\n\n";
const TERMINAL_OPERATIONS: [&str; 4] = ["fetch", "get", "list", "search"];
const HTTP_METHODS: [&str; 5] = ["get", "post", "put", "patch", "delete"];

pub fn run(root: &Path, check: bool) -> Result<(), String> {
    let input_path = root.join("openapi").join("openhandle.json");
    let input = std::fs::read_to_string(&input_path)
        .map_err(|error| format!("read {}: {error}", input_path.display()))?;
    let document: Value = serde_json::from_str(&input)
        .map_err(|error| format!("decode OpenAPI contract: {error}"))?;
    let schemas = document["components"]["schemas"]
        .as_object()
        .ok_or("OpenAPI contract has no component schemas")?;
    let operations = operations(&document)?;

    let models = Models::generate(schemas)?;
    let resources = Resources::generate(&operations, schemas, &models.names)?;
    let surface = generate_surface(&operations, &resources.operation_types)?;

    let files = [
        ("mod.rs", generate_module()),
        ("models.rs", models.output),
        ("resources.rs", resources.output),
        ("surface.rs", surface),
    ];
    let directory = root.join("src").join("generated");
    if !check {
        std::fs::create_dir_all(&directory)
            .map_err(|error| format!("create {}: {error}", directory.display()))?;
    }
    for (name, contents) in files {
        let formatted = rustfmt(&contents).map_err(|error| format!("format {name}: {error}"))?;
        let target = directory.join(name);
        if check {
            let current = std::fs::read_to_string(&target).unwrap_or_default();
            if current != formatted {
                return Err(format!(
                    "src/generated/{name} is stale; run `cargo xtask generate`"
                ));
            }
            continue;
        }
        std::fs::write(&target, formatted)
            .map_err(|error| format!("write {}: {error}", target.display()))?;
    }
    Ok(())
}

#[derive(Clone)]
struct ScopeSegment {
    name: String,
    parameter: Option<String>,
    reference: Option<String>,
}

#[derive(Clone)]
struct Parameter {
    name: String,
    required: bool,
    description: String,
    schema: Value,
}

#[derive(Clone)]
struct Operation {
    api_path: String,
    method: String,
    sdk_path: String,
    scope: Vec<ScopeSegment>,
    operation: String,
    paginated: bool,
    summary: String,
    description: String,
    query: Vec<Parameter>,
    response: Value,
}

fn operations(document: &Value) -> Result<Vec<Operation>, String> {
    let paths = document["paths"]
        .as_object()
        .ok_or("OpenAPI contract has no paths")?;
    let mut result = Vec::new();
    let mut seen = BTreeSet::new();
    for (api_path, item) in paths {
        let item = item
            .as_object()
            .ok_or_else(|| format!("{api_path} is not an object"))?;
        for (method, value) in item {
            if !HTTP_METHODS.contains(&method.as_str()) {
                continue;
            }
            let label = format!("{} {api_path}", method.to_uppercase());
            let sdk = &value["x-openhandle-sdk"];
            let sdk_path = sdk["path"].as_str().unwrap_or_default().to_owned();
            let operation = sdk["operation"].as_str().unwrap_or_default().to_owned();
            let scope = sdk["scope"]
                .as_array()
                .ok_or_else(|| format!("{label} has no valid x-openhandle-sdk mapping"))?
                .iter()
                .map(|segment| ScopeSegment {
                    name: segment["name"].as_str().unwrap_or_default().to_owned(),
                    parameter: segment["parameter"].as_str().map(str::to_owned),
                    reference: segment["reference"].as_str().map(str::to_owned),
                })
                .collect::<Vec<_>>();
            if sdk_path.is_empty() || (scope.is_empty() && operation != "fetch") {
                return Err(format!("{label} has no valid x-openhandle-sdk mapping"));
            }
            if !TERMINAL_OPERATIONS.contains(&operation.as_str()) {
                return Err(format!(
                    "{label} uses unsupported terminal operation {operation}"
                ));
            }
            if scope.iter().any(|segment| segment.name.is_empty()) {
                return Err(format!("{label} has an unnamed scope segment"));
            }
            if !seen.insert(sdk_path.clone()) {
                return Err(format!("duplicate SDK path {sdk_path}"));
            }
            let bound: BTreeSet<&str> = scope
                .iter()
                .filter_map(|segment| segment.parameter.as_deref())
                .collect();
            let placeholders: BTreeSet<&str> = api_path
                .split('{')
                .skip(1)
                .filter_map(|part| part.split('}').next())
                .collect();
            if bound != placeholders {
                return Err(format!(
                    "{label} does not bind every path parameter in its scope"
                ));
            }
            let query = value["parameters"]
                .as_array()
                .map(Vec::as_slice)
                .unwrap_or_default()
                .iter()
                .filter(|parameter| parameter["in"] == "query")
                .map(|parameter| Parameter {
                    name: parameter["name"].as_str().unwrap_or_default().to_owned(),
                    required: parameter["required"].as_bool().unwrap_or(false),
                    description: parameter["description"]
                        .as_str()
                        .unwrap_or_default()
                        .to_owned(),
                    schema: parameter["schema"].clone(),
                })
                .collect();
            let response =
                value["responses"]["200"]["content"]["application/json"]["schema"].clone();
            if response.is_null() {
                return Err(format!("{label} has no JSON 200 response"));
            }
            result.push(Operation {
                api_path: api_path.clone(),
                method: method.clone(),
                sdk_path,
                scope,
                operation,
                paginated: sdk["paginated"].as_bool().unwrap_or(false),
                summary: value["summary"].as_str().unwrap_or_default().to_owned(),
                description: value["description"].as_str().unwrap_or_default().to_owned(),
                query,
                response,
            });
        }
    }
    result.sort_by(|left, right| left.sdk_path.cmp(&right.sdk_path));
    Ok(result)
}

fn generate_module() -> String {
    format!(
        "{HEADER}//! Code generated from the pinned OpenAPI contract.\n\n\
         pub mod models;\npub mod resources;\n#[cfg(test)]\npub(crate) mod surface;\n"
    )
}

struct Models {
    output: String,
    names: BTreeSet<String>,
}

struct ModelWriter<'a> {
    schemas: &'a Map<String, Value>,
    output: String,
    names: BTreeSet<String>,
    queue: VecDeque<(String, Value)>,
    structures: Vec<Structure>,
}

struct Structure {
    name: String,
    documentation: String,
    fields: Vec<Field>,
    position: usize,
}

struct Field {
    documentation: String,
    attributes: Vec<String>,
    name: String,
    value_type: String,
}

impl Models {
    fn generate(schemas: &Map<String, Value>) -> Result<Models, String> {
        let mut writer = ModelWriter {
            schemas,
            output: String::new(),
            names: schemas.keys().cloned().collect(),
            queue: VecDeque::new(),
            structures: Vec::new(),
        };
        writer.output.push_str(HEADER);
        writer
            .output
            .push_str("//! Response models generated from the OpenAPI component schemas.\n\n");
        writer
            .output
            .push_str("use serde::{Deserialize, Serialize};\n\n");
        for (name, schema) in schemas {
            writer.declare(name, schema)?;
        }
        while let Some((name, schema)) = writer.queue.pop_front() {
            writer.structure(&name, &schema)?;
        }
        Ok(Models {
            output: writer.render(),
            names: writer.names,
        })
    }
}

impl ModelWriter<'_> {
    fn declare(&mut self, name: &str, schema: &Value) -> Result<(), String> {
        if let Some(reference) = schema["$ref"].as_str() {
            let target = reference_name(reference);
            writeln!(self.output, "/// The `{name}` model, which has the shape of [`{target}`].\npub type {name} = {target};\n").unwrap();
            return Ok(());
        }
        if let Some(variants) = schema["oneOf"].as_array() {
            return self.one_of(name, variants);
        }
        if has_type(schema, "object") || schema["properties"].is_object() {
            return self.structure(name, schema);
        }
        let target = self.rust_type(schema, true, name)?;
        writeln!(
            self.output,
            "/// The `{name}` model.\npub type {name} = {target};\n"
        )
        .unwrap();
        Ok(())
    }

    fn one_of(&mut self, name: &str, variants: &[Value]) -> Result<(), String> {
        let mut body = String::new();
        for variant in variants {
            let (variant_name, variant_type, documentation) = if has_type(variant, "string") {
                let values = enum_values(variant);
                let documentation = if values.is_empty() {
                    "A text value.".to_owned()
                } else {
                    format!("A text value: {values}.")
                };
                ("Text", "String", documentation)
            } else if has_type(variant, "integer") {
                ("Integer", "i64", "An integer value.".to_owned())
            } else if has_type(variant, "number") {
                ("Number", "f64", "A number value.".to_owned())
            } else if has_type(variant, "boolean") {
                ("Boolean", "bool", "A boolean value.".to_owned())
            } else {
                return Err(format!("{name} uses an unsupported oneOf variant"));
            };
            writeln!(
                body,
                "    /// {documentation}\n    {variant_name}({variant_type}),"
            )
            .unwrap();
        }
        writeln!(
            self.output,
            "/// The `{name}` model. It holds one of several value types.\n\
             #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]\n\
             #[serde(untagged)]\n\
             #[non_exhaustive]\n\
             pub enum {name} {{\n{body}}}\n"
        )
        .unwrap();
        Ok(())
    }

    fn structure(&mut self, name: &str, schema: &Value) -> Result<(), String> {
        let required: BTreeSet<&str> = schema["required"]
            .as_array()
            .map(Vec::as_slice)
            .unwrap_or_default()
            .iter()
            .filter_map(Value::as_str)
            .collect();
        let empty = Map::new();
        let properties = schema["properties"].as_object().unwrap_or(&empty);
        let mut fields = Vec::new();
        let mut field_names = BTreeSet::new();
        for (property, property_schema) in properties {
            let field = field_name(property);
            if !field_names.insert(field.clone()) {
                return Err(format!("{name} has two properties named {field}"));
            }
            let value_type = self.rust_type(
                property_schema,
                required.contains(property.as_str()),
                &format!("{name}{}", pascal_case(property)),
            )?;
            let mut attributes = Vec::new();
            if field.trim_start_matches("r#") != property {
                attributes.push(format!("rename = {property:?}"));
            }
            let documentation = match property_schema["description"].as_str() {
                Some(description) => doc_comment(description, "    "),
                None => format!("    /// The `{property}` field.\n"),
            };
            fields.push(Field {
                documentation,
                attributes,
                name: field,
                value_type,
            });
        }
        let documentation = schema["description"]
            .as_str()
            .map(|description| doc_comment(description, ""))
            .unwrap_or_else(|| format!("/// The `{name}` model.\n"));
        self.structures.push(Structure {
            name: name.to_owned(),
            documentation,
            fields,
            position: self.output.len(),
        });
        Ok(())
    }

    fn render(&self) -> String {
        let mut output = String::new();
        let mut written = 0;
        for structure in &self.structures {
            let position = structure.position.max(written);
            output.push_str(&self.output[written..position]);
            written = position;
            let mut fields = String::new();
            for field in &structure.fields {
                let value_type = match by_value_target(&field.value_type)
                    .filter(|target| self.names.contains(*target))
                {
                    Some(target) => field
                        .value_type
                        .replacen(target, &format!("Box<{target}>"), 1),
                    None => field.value_type.clone(),
                };
                let mut attributes = field.attributes.clone();
                if !value_type.starts_with("Option<") && value_type != "serde_json::Value" {
                    attributes.push("deserialize_with = \"crate::de::null_as_default\"".to_owned());
                }
                fields.push_str(&field.documentation);
                if !attributes.is_empty() {
                    writeln!(fields, "    #[serde({})]", attributes.join(", ")).unwrap();
                }
                writeln!(fields, "    pub {}: {value_type},", field.name).unwrap();
            }
            write!(
                output,
                "{}#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]\n\
                 #[serde(default)]\n\
                 #[non_exhaustive]\n\
                 pub struct {} {{\n{fields}}}\n\n",
                structure.documentation, structure.name
            )
            .unwrap();
        }
        output.push_str(&self.output[written..]);
        output
    }

    fn rust_type(
        &mut self,
        schema: &Value,
        required: bool,
        inline_name: &str,
    ) -> Result<String, String> {
        if let Some(variants) = schema["anyOf"].as_array() {
            let Some(variant) = variants.iter().find(|variant| !is_null_schema(variant)) else {
                return Ok("serde_json::Value".to_owned());
            };
            let inner = self.rust_type(variant, true, inline_name)?;
            return Ok(optional(inner));
        }
        let nullable = has_type(schema, "null") || !required;
        let base = if let Some(reference) = schema["$ref"].as_str() {
            reference_name(reference)
        } else if schema.get("oneOf").is_some() || schema.get("allOf").is_some() {
            return Err(format!(
                "{inline_name} uses an unsupported inline composition"
            ));
        } else if has_type(schema, "array") {
            match schema.get("items") {
                Some(items) if !is_empty_schema(items) => {
                    format!(
                        "Vec<{}>",
                        self.rust_type(items, true, &format!("{inline_name}Item"))?
                    )
                }
                _ => "Vec<serde_json::Value>".to_owned(),
            }
        } else if has_type(schema, "object") || schema["properties"].is_object() {
            if schema["properties"]
                .as_object()
                .is_some_and(|properties| !properties.is_empty())
            {
                if self.schemas.contains_key(inline_name)
                    || !self.names.insert(inline_name.to_owned())
                {
                    return Err(format!("inline model name {inline_name} is not unique"));
                }
                self.queue
                    .push_back((inline_name.to_owned(), schema.clone()));
                inline_name.to_owned()
            } else {
                match schema.get("additionalProperties") {
                    Some(additional) if additional.is_object() && !is_empty_schema(additional) => {
                        format!(
                            "std::collections::BTreeMap<String, {}>",
                            self.rust_type(additional, true, &format!("{inline_name}Value"))?
                        )
                    }
                    _ => "serde_json::Map<String, serde_json::Value>".to_owned(),
                }
            }
        } else if has_type(schema, "integer") {
            "i64".to_owned()
        } else if has_type(schema, "number") {
            "f64".to_owned()
        } else if has_type(schema, "boolean") || schema["const"].is_boolean() {
            "bool".to_owned()
        } else if has_type(schema, "string") && schema["format"] == "date-time" {
            "chrono::DateTime<chrono::Utc>".to_owned()
        } else if has_type(schema, "string") || schema["const"].is_string() {
            "String".to_owned()
        } else {
            return Ok("serde_json::Value".to_owned());
        };
        Ok(if nullable { optional(base) } else { base })
    }
}

struct Node {
    path: Vec<String>,
    scope: Option<ScopeSegment>,
    children: BTreeMap<String, Node>,
    operations: BTreeMap<String, Operation>,
}

impl Node {
    fn new(path: Vec<String>, scope: Option<ScopeSegment>) -> Self {
        Self {
            path,
            scope,
            children: BTreeMap::new(),
            operations: BTreeMap::new(),
        }
    }

    fn type_name(&self) -> String {
        format!(
            "{}Resource",
            self.path
                .iter()
                .map(|name| pascal_case(name))
                .collect::<String>()
        )
    }
}

struct OperationType {
    options: Option<String>,
    required: Vec<Parameter>,
}

struct Resources {
    output: String,
    operation_types: BTreeMap<String, OperationType>,
}

struct ResourceWriter<'a> {
    schemas: &'a Map<String, Value>,
    output: String,
    types: String,
    declared: BTreeSet<String>,
    operation_types: BTreeMap<String, OperationType>,
}

impl Resources {
    fn generate(
        operations: &[Operation],
        schemas: &Map<String, Value>,
        model_names: &BTreeSet<String>,
    ) -> Result<Resources, String> {
        let mut root = Node::new(Vec::new(), None);
        for operation in operations {
            let mut node = &mut root;
            for segment in &operation.scope {
                let path = [node.path.clone(), vec![segment.name.clone()]].concat();
                node = node
                    .children
                    .entry(segment.name.clone())
                    .or_insert_with(|| Node::new(path, Some(segment.clone())));
                let existing = node
                    .scope
                    .as_ref()
                    .map(|scope| (&scope.parameter, &scope.reference));
                if existing != Some((&segment.parameter, &segment.reference)) {
                    return Err(format!(
                        "{} redefines scope segment {}",
                        operation.sdk_path, segment.name
                    ));
                }
            }
            if node
                .operations
                .insert(operation.operation.clone(), operation.clone())
                .is_some()
            {
                return Err(format!(
                    "{} duplicates a terminal operation",
                    operation.sdk_path
                ));
            }
        }

        let mut writer = ResourceWriter {
            schemas,
            output: String::new(),
            types: String::new(),
            declared: model_names.clone(),
            operation_types: BTreeMap::new(),
        };
        writer.output.push_str(HEADER);
        writer.output.push_str(
            "//! The resource graph, operation options, and response types generated from the\n\
             //! `x-openhandle-sdk` operation metadata.\n\n\
             use std::time::Duration;\n\n\
             use reqwest::Method;\n\n\
             use super::models::*;\n\
             use crate::client::Client;\n\
             use crate::errors::Error;\n\
             use crate::options::{FetchOptions, Query, RequestOptions};\n\
             use crate::references::{ProfileReference, Reference, ResourceReference};\n\
             use crate::response::{Items, Page, Response};\n\
             use crate::transport::Scope;\n\n",
        );
        writer.client(&root)?;
        let mut nodes = Vec::new();
        collect_nodes(&root, &mut nodes);
        for node in nodes {
            writer.node(node)?;
        }
        let ResourceWriter {
            mut output,
            types,
            operation_types,
            ..
        } = writer;
        output.push_str(&types);
        Ok(Resources {
            output,
            operation_types,
        })
    }
}

fn collect_nodes<'a>(node: &'a Node, result: &mut Vec<&'a Node>) {
    for child in node.children.values() {
        result.push(child);
        collect_nodes(child, result);
    }
}

impl ResourceWriter<'_> {
    fn declare(&mut self, name: &str) -> Result<(), String> {
        if self.declared.insert(name.to_owned()) {
            return Ok(());
        }
        Err(format!("generated type name {name} is not unique"))
    }

    fn client(&mut self, root: &Node) -> Result<(), String> {
        let mut methods = String::new();
        for (name, child) in &root.children {
            let child_type = child.type_name();
            writeln!(
                methods,
                "    /// Selects the {} resources. This never sends a request.\n    \
                 pub fn {}(&self) -> {child_type} {{\n        {child_type} {{ scope: Scope::new(self.clone()) }}\n    }}\n",
                display_name(name),
                method_name(name),
            )
            .unwrap();
        }
        if let Some(operation) = root.operations.get("fetch") {
            self.fetch(operation, &mut methods)?;
        }
        if root.operations.keys().any(|name| name != "fetch") {
            return Err("only fetch may be a root operation".to_owned());
        }
        writeln!(self.output, "impl Client {{\n{methods}}}\n").unwrap();
        Ok(())
    }

    fn fetch(&mut self, operation: &Operation, methods: &mut String) -> Result<(), String> {
        let variants = operation.response["oneOf"]
            .as_array()
            .ok_or("fetch must return a oneOf response")?;
        let mut enum_body = String::new();
        let mut decode_arms = String::new();
        for variant in variants {
            let parts = variant["allOf"]
                .as_array()
                .ok_or("fetch variants must use allOf")?;
            let properties = parts
                .iter()
                .find(|part| part["properties"]["data"].is_object())
                .map(|part| &part["properties"])
                .ok_or("fetch variant has no data")?;
            let platform = properties["platform"]["const"]
                .as_str()
                .ok_or("fetch variant has no platform")?;
            let resource = properties["resource"]["const"]
                .as_str()
                .ok_or("fetch variant has no resource")?;
            let model = properties["data"]["$ref"]
                .as_str()
                .map(reference_name)
                .ok_or("fetch variant data must reference a model")?;
            writeln!(
                enum_body,
                "    /// A {platform} {resource}.\n    {model}(Box<{model}>),"
            )
            .unwrap();
            writeln!(
                decode_arms,
                "            ({platform:?}, {resource:?}) => serde_json::from_value(data).map(|value| Some(Self::{model}(Box::new(value)))),"
            )
            .unwrap();
        }
        self.declare("FetchResource")?;
        self.declare("FetchResponse")?;
        writeln!(
            self.types,
            "/// The resource returned by [`Client::fetch`]. The variant follows the\n\
             /// platform and resource the URL represents.\n\
             #[derive(Clone, Debug, PartialEq)]\n\
             #[non_exhaustive]\n\
             pub enum FetchResource {{\n{enum_body}}}\n\n\
             impl FetchResource {{\n    \
             pub(crate) fn decode(platform: &str, resource: &str, data: serde_json::Value) -> Result<Option<Self>, serde_json::Error> {{\n        \
             match (platform, resource) {{\n{decode_arms}            _ => Ok(None),\n        }}\n    }}\n}}\n\n\
             /// Typed result of [`Client::fetch`].\n\
             pub type FetchResponse = Response<FetchResource>;\n"
        )
        .unwrap();
        self.operation_types.insert(
            operation.sdk_path.clone(),
            OperationType {
                options: None,
                required: Vec::new(),
            },
        );
        write!(
            methods,
            "{}    pub async fn fetch(&self, url: &str, options: impl Into<Option<FetchOptions>>) -> Result<FetchResponse, Error> {{\n        \
             let options = options.into().unwrap_or_default();\n        \
             Scope::new(self.clone())\n            .fetch(url, options.freshness, options.request_options)?\n            .send_fetch()\n            .await\n    }}\n",
            operation_documentation(operation),
        )
        .unwrap();
        Ok(())
    }

    fn node(&mut self, node: &Node) -> Result<(), String> {
        let type_name = node.type_name();
        self.declare(&type_name)?;
        let platform = &node.path[0];
        let mut methods = String::new();
        let mut member_names = BTreeSet::new();
        for (name, child) in &node.children {
            let child_type = child.type_name();
            let member = method_name(name);
            if !member_names.insert(member.clone()) {
                return Err(format!("{type_name} has two members named {member}"));
            }
            let scope = child.scope.as_ref().expect("child nodes have a scope");
            let Some(parameter) = &scope.parameter else {
                let allowance = if member == "new" {
                    "    #[allow(clippy::new_ret_no_self)]\n"
                } else {
                    ""
                };
                writeln!(
                    methods,
                    "    /// Selects the {} resources. This never sends a request.\n{allowance}    \
                     pub fn {member}(&self) -> {child_type} {{\n        {child_type} {{ scope: self.scope.clone() }}\n    }}\n",
                    display_name(name),
                )
                .unwrap();
                continue;
            };
            let reference = scope.reference.clone().unwrap_or_else(|| name.clone());
            let (reference_type, documentation) = if reference == "profile" {
                (
                    "ProfileReference",
                    "A raw string is a username unless it is a supported social URL. Pass\n    \
                     /// [`Username`](crate::Username), [`Id`](crate::Id), or [`Url`](crate::Url) to state the meaning.",
                )
            } else {
                (
                    "ResourceReference",
                    "A raw string is the native ID or shorthand unless it is a supported social\n    \
                     /// URL. Pass [`Id`](crate::Id) or [`Url`](crate::Url) to state the meaning.",
                )
            };
            writeln!(
                methods,
                "    /// Selects one {}. This never sends a request.\n    ///\n    /// {documentation}\n    /// An invalid reference fails the first operation, before any request.\n    \
                 pub fn {member}(&self, reference: impl Into<{reference_type}>) -> {child_type} {{\n        \
                 {child_type} {{ scope: self.scope.select({parameter:?}, {platform:?}, {reference:?}, Reference::from(reference.into())) }}\n    }}\n",
                display_name(name),
            )
            .unwrap();
        }
        for (name, operation) in &node.operations {
            let member = method_name(name);
            if !member_names.insert(member.clone()) {
                return Err(format!("{type_name} has two members named {member}"));
            }
            self.operation(operation, &member, &mut methods, &mut member_names)?;
        }
        let documentation = match &node.scope {
            Some(ScopeSegment {
                parameter: Some(_), ..
            }) => format!(
                "/// One selected {} on {}.",
                display_name(node.path.last().expect("nodes have a path")),
                display_name(platform),
            ),
            _ => format!("/// The `{}` resources.", node.path.join(".")),
        };
        writeln!(
            self.output,
            "{documentation}\n///\n/// Selecting a resource never sends a request. Only its terminal operations do.\n\
             #[derive(Clone, Debug)]\n\
             pub struct {type_name} {{\n    scope: Scope,\n}}\n\n\
             impl {type_name} {{\n{methods}}}\n"
        )
        .unwrap();
        Ok(())
    }

    fn operation(
        &mut self,
        operation: &Operation,
        member: &str,
        methods: &mut String,
        member_names: &mut BTreeSet<String>,
    ) -> Result<(), String> {
        let base = operation_type_base(operation);
        let options_type = format!("{base}Options");
        let required: Vec<Parameter> = operation
            .query
            .iter()
            .filter(|parameter| parameter.required)
            .cloned()
            .collect();
        self.options(operation, &options_type, &required)?;
        let data_type = self.data_type(operation)?;
        let options_argument = if required.is_empty() {
            format!("options: impl Into<Option<{options_type}>>")
        } else {
            format!("options: {options_type}")
        };
        let options_value = if required.is_empty() {
            "let options = options.into().unwrap_or_default();\n        "
        } else {
            ""
        };
        let method = operation.method.to_uppercase();
        let api_path = &operation.api_path;
        let request = format!(
            "self.scope.operation(Method::{method}, {api_path:?}, options.query(), options.request_options)"
        );
        let documentation = operation_documentation(operation);
        if operation.paginated {
            let page_type = format!("{base}Page");
            self.declare(&page_type)?;
            writeln!(
                self.types,
                "/// One page returned by `{}`.\npub type {page_type} = Page<{data_type}>;\n",
                operation.sdk_path
            )
            .unwrap();
            let items_member = if operation.operation == "list" {
                "items".to_owned()
            } else {
                format!("{member}_items")
            };
            if !member_names.insert(items_member.clone()) {
                return Err(format!(
                    "{} has two members named {items_member}",
                    operation.sdk_path
                ));
            }
            write!(
                methods,
                "{documentation}    pub async fn {member}(&self, {options_argument}) -> Result<{page_type}, Error> {{\n        \
                 {options_value}{request}?.send_page().await\n    }}\n\n\
                 /// Iterates lazily over every item of [`{member}`](Self::{member}), one page per request.\n    \
                 pub fn {items_member}(&self, {options_argument}) -> Items<{data_type}> {{\n        \
                 {options_value}Items::new({request})\n    }}\n\n"
            )
            .unwrap();
        } else {
            let response_type = format!("{base}Response");
            self.declare(&response_type)?;
            writeln!(
                self.types,
                "/// Typed result of `{}`.\npub type {response_type} = Response<{data_type}>;\n",
                operation.sdk_path
            )
            .unwrap();
            write!(
                methods,
                "{documentation}    pub async fn {member}(&self, {options_argument}) -> Result<{response_type}, Error> {{\n        \
                 {options_value}{request}?.send().await\n    }}\n\n"
            )
            .unwrap();
        }
        self.operation_types.insert(
            operation.sdk_path.clone(),
            OperationType {
                options: Some(options_type),
                required,
            },
        );
        Ok(())
    }

    fn options(
        &mut self,
        operation: &Operation,
        options_type: &str,
        required: &[Parameter],
    ) -> Result<(), String> {
        self.declare(options_type)?;
        let mut fields = String::new();
        let mut setters = String::new();
        let mut query = String::new();
        let mut member_names: BTreeSet<String> =
            ["new", "max_retries", "timeout", "query", "request_options"]
                .map(str::to_owned)
                .into();
        for parameter in &operation.query {
            let field = field_name(&parameter.name);
            if !member_names.insert(field.clone()) {
                return Err(format!("{options_type} has two members named {field}"));
            }
            let value_type = option_value_type(parameter);
            let documentation = parameter_documentation(parameter);
            let name = &parameter.name;
            if parameter.required {
                writeln!(fields, "{documentation}    pub {field}: {value_type},").unwrap();
                writeln!(query, "        query.require({name:?}, &self.{field})?;").unwrap();
            } else {
                writeln!(
                    fields,
                    "{documentation}    pub {field}: Option<{value_type}>,"
                )
                .unwrap();
                writeln!(query, "        query.push({name:?}, &self.{field});").unwrap();
                let (argument, value) = if value_type == "String" {
                    ("impl Into<String>".to_owned(), "value.into()")
                } else {
                    (value_type.clone(), "value")
                };
                write!(
                    setters,
                    "{documentation}    pub fn {field}(mut self, value: {argument}) -> Self {{\n        self.{field} = Some({value});\n        self\n    }}\n\n"
                )
                .unwrap();
            }
        }
        let (derives, constructor) = if required.is_empty() {
            (
                "Clone, Debug, Default, PartialEq",
                "    /// Creates options that use the API and client defaults.\n    \
                 pub fn new() -> Self {\n        Self::default()\n    }\n\n"
                    .to_owned(),
            )
        } else {
            let arguments = required
                .iter()
                .map(|parameter| format!("{}: impl Into<String>", field_name(&parameter.name)))
                .collect::<Vec<_>>()
                .join(", ");
            let assignments = required
                .iter()
                .map(|parameter| {
                    let field = field_name(&parameter.name);
                    format!("{field}: {field}.into()")
                })
                .collect::<Vec<_>>()
                .join(", ");
            let optional = operation
                .query
                .iter()
                .filter(|parameter| !parameter.required)
                .map(|parameter| format!("{}: None", field_name(&parameter.name)))
                .chain(["request_options: RequestOptions::default()".to_owned()])
                .collect::<Vec<_>>()
                .join(", ");
            if required
                .iter()
                .any(|parameter| option_value_type(parameter) != "String")
            {
                return Err(format!(
                    "{options_type} has a required option that is not a string"
                ));
            }
            (
                "Clone, Debug, PartialEq",
                format!(
                    "    /// Creates options with the required values.\n    \
                     pub fn new({arguments}) -> Self {{\n        Self {{ {assignments}, {optional} }}\n    }}\n\n"
                ),
            )
        };
        let query_body = if query.is_empty() {
            "        Ok(Query::default())\n".to_owned()
        } else {
            format!("        let mut query = Query::default();\n{query}        Ok(query)\n")
        };
        writeln!(
            self.types,
            "/// Options for `{sdk_path}`.\n\
             #[derive({derives})]\n\
             #[non_exhaustive]\n\
             pub struct {options_type} {{\n{fields}    /// Retry and timeout controls for this request.\n    pub request_options: RequestOptions,\n}}\n\n\
             impl {options_type} {{\n{constructor}{setters}    \
             /// Sets the retry attempts after the first request.\n    \
             pub fn max_retries(mut self, value: u32) -> Self {{\n        self.request_options.max_retries = Some(value);\n        self\n    }}\n\n    \
             /// Sets the timeout for each attempt.\n    \
             pub fn timeout(mut self, value: Duration) -> Self {{\n        self.request_options.timeout = Some(value);\n        self\n    }}\n\n    \
             pub(crate) fn query(&self) -> Result<Query, Error> {{\n{query_body}    }}\n}}\n",
            sdk_path = operation.sdk_path,
        )
        .unwrap();
        Ok(())
    }

    fn data_type(&self, operation: &Operation) -> Result<String, String> {
        let data = find_property(self.schemas, &operation.response, "data")
            .ok_or_else(|| format!("{} response has no data schema", operation.sdk_path))?;
        if operation.paginated {
            let items = data
                .get("items")
                .filter(|_| has_type(&data, "array"))
                .ok_or_else(|| {
                    format!(
                        "{} is paginated but its data is not an array",
                        operation.sdk_path
                    )
                })?;
            return simple_type(items)
                .ok_or_else(|| format!("{} has an unsupported item type", operation.sdk_path));
        }
        simple_type(&data)
            .ok_or_else(|| format!("{} has an unsupported data type", operation.sdk_path))
    }
}

fn generate_surface(
    operations: &[Operation],
    operation_types: &BTreeMap<String, OperationType>,
) -> Result<String, String> {
    let mut calls = String::new();
    for operation in operations {
        let types = operation_types
            .get(&operation.sdk_path)
            .ok_or_else(|| format!("{} has no generated types", operation.sdk_path))?;
        let call = if operation.operation == "fetch" {
            "client.fetch(\"https://www.instagram.com/openai/\", None)".to_owned()
        } else {
            let mut chain = "client".to_owned();
            for segment in &operation.scope {
                let member = method_name(&segment.name);
                match &segment.parameter {
                    Some(parameter) => {
                        write!(chain, ".{member}(crate::Id::new(\"sample-{parameter}\"))").unwrap()
                    }
                    None => write!(chain, ".{member}()").unwrap(),
                }
            }
            let options_type = types.options.as_ref().expect("operations have options");
            let options = if types.required.is_empty() {
                "None".to_owned()
            } else {
                let arguments = types
                    .required
                    .iter()
                    .map(|parameter| format!("\"sample-{}\"", parameter.name))
                    .collect::<Vec<_>>()
                    .join(", ");
                format!("crate::{options_type}::new({arguments})")
            };
            format!("{chain}.{}({options})", method_name(&operation.operation))
        };
        writeln!(
            calls,
            "    results.push(({:?}, Box::pin({call}).await.map(|_| ())));",
            operation.sdk_path
        )
        .unwrap();
    }
    Ok(format!(
        "{HEADER}//! Calls every operation once through the public resource graph.\n\n\
         use crate::{{Client, Error}};\n\n\
         pub(crate) async fn call_every_operation(client: &Client) -> Vec<(&'static str, Result<(), Error>)> {{\n    \
         let mut results = Vec::new();\n{calls}    results\n}}\n"
    ))
}

fn by_value_target(value_type: &str) -> Option<&str> {
    let inner = value_type
        .strip_prefix("Option<")
        .and_then(|inner| inner.strip_suffix('>'))
        .unwrap_or(value_type);
    inner
        .chars()
        .all(|character| character.is_ascii_alphanumeric())
        .then_some(inner)
        .filter(|inner| inner.starts_with(|character: char| character.is_ascii_uppercase()))
}

fn find_property(schemas: &Map<String, Value>, schema: &Value, name: &str) -> Option<Value> {
    if let Some(reference) = schema["$ref"].as_str() {
        return find_property(schemas, schemas.get(&reference_name(reference))?, name);
    }
    if let Some(property) = schema["properties"].get(name) {
        return Some(property.clone());
    }
    schema["allOf"]
        .as_array()?
        .iter()
        .rev()
        .find_map(|part| find_property(schemas, part, name))
}

fn simple_type(schema: &Value) -> Option<String> {
    if let Some(reference) = schema["$ref"].as_str() {
        return Some(reference_name(reference));
    }
    if has_type(schema, "array") {
        return Some(format!("Vec<{}>", simple_type(schema.get("items")?)?));
    }
    None
}

fn option_value_type(parameter: &Parameter) -> String {
    match parameter.name.as_str() {
        "freshness" => "crate::options::Freshness".to_owned(),
        "platform" => "crate::options::Platform".to_owned(),
        _ if has_type(&parameter.schema, "integer") => "i64".to_owned(),
        _ if has_type(&parameter.schema, "boolean") => "bool".to_owned(),
        _ if parameter.schema["format"] == "date-time" => {
            "chrono::DateTime<chrono::Utc>".to_owned()
        }
        _ => "String".to_owned(),
    }
}

fn parameter_documentation(parameter: &Parameter) -> String {
    let mut text = parameter.description.trim().to_owned();
    if text.is_empty() {
        text = format!("The `{}` query parameter.", parameter.name);
    }
    let values = enum_values(&parameter.schema);
    if !values.is_empty() && parameter.name != "freshness" && parameter.name != "platform" {
        write!(text, " One of {values}.").unwrap();
    }
    if let Some(default) = parameter.schema.get("default") {
        let default = default
            .as_str()
            .map_or_else(|| default.to_string(), str::to_owned);
        if !text.contains("default") {
            write!(text, " The API default is `{default}`.").unwrap();
        }
    }
    if let (Some(minimum), Some(maximum)) = (
        parameter.schema["minimum"].as_i64(),
        parameter.schema["maximum"].as_i64(),
    ) {
        write!(text, " Accepts {minimum} to {maximum}.").unwrap();
    }
    doc_comment(&text, "    ")
}

fn operation_documentation(operation: &Operation) -> String {
    let mut text = String::new();
    if !operation.summary.is_empty() {
        writeln!(text, "{}.", operation.summary.trim_end_matches('.')).unwrap();
    }
    if !operation.description.is_empty() {
        writeln!(text, "\n{}", operation.description.trim()).unwrap();
    }
    write!(
        text,
        "\n`{} {}`",
        operation.method.to_uppercase(),
        operation.api_path
    )
    .unwrap();
    doc_comment(&text, "    ")
}

fn enum_values(schema: &Value) -> String {
    let values: Vec<String> = schema["enum"]
        .as_array()
        .map(Vec::as_slice)
        .unwrap_or_default()
        .iter()
        .map(|value| {
            format!(
                "`{}`",
                value
                    .as_str()
                    .map_or_else(|| value.to_string(), str::to_owned)
            )
        })
        .collect();
    match values.as_slice() {
        [] => String::new(),
        [single] => single.clone(),
        [first @ .., last] => format!("{}, or {last}", first.join(", ")),
    }
}

fn doc_comment(text: &str, indent: &str) -> String {
    let mut result = String::new();
    for line in wrap(text) {
        if line.is_empty() {
            writeln!(result, "{indent}///").unwrap();
        } else {
            writeln!(result, "{indent}/// {line}").unwrap();
        }
    }
    result
}

fn wrap(text: &str) -> Vec<String> {
    let mut lines = Vec::new();
    for paragraph in text.lines() {
        if paragraph.trim().is_empty() {
            lines.push(String::new());
            continue;
        }
        let mut line = String::new();
        for word in paragraph.split_whitespace() {
            if !line.is_empty() && line.len() + word.len() + 1 > 80 {
                lines.push(std::mem::take(&mut line));
            }
            if !line.is_empty() {
                line.push(' ');
            }
            line.push_str(word);
        }
        lines.push(line);
    }
    lines
}

fn operation_type_base(operation: &Operation) -> String {
    let mut name: String = operation
        .scope
        .iter()
        .map(|segment| pascal_case(&segment.name))
        .collect();
    if operation.operation == "search" {
        name.push_str("Search");
    }
    name
}

fn display_name(name: &str) -> String {
    match name {
        "tiktok" => "TikTok".to_owned(),
        "twitter" => "X (Twitter)".to_owned(),
        "instagram" => "Instagram".to_owned(),
        "reddit" => "Reddit".to_owned(),
        "testData" => "Test data catalog".to_owned(),
        _ => snake_case(name).replace('_', " "),
    }
}

fn reference_name(reference: &str) -> String {
    reference.rsplit('/').next().unwrap_or(reference).to_owned()
}

fn has_type(schema: &Value, expected: &str) -> bool {
    match &schema["type"] {
        Value::String(value) => value == expected,
        Value::Array(values) => values.iter().any(|value| value == expected),
        _ => false,
    }
}

fn is_null_schema(schema: &Value) -> bool {
    schema["type"] == "null"
}

fn is_empty_schema(schema: &Value) -> bool {
    schema.as_object().is_some_and(Map::is_empty)
}

fn optional(inner: String) -> String {
    if inner.starts_with("Option<") || inner == "serde_json::Value" {
        return inner;
    }
    format!("Option<{inner}>")
}

pub fn pascal_case(value: &str) -> String {
    match value {
        "tiktok" => return "TikTok".to_owned(),
        "oembed" => return "OEmbed".to_owned(),
        _ => {}
    }
    let mut result = String::with_capacity(value.len());
    let mut uppercase_next = true;
    for character in value.chars() {
        if matches!(character, '_' | '-' | ' ') {
            uppercase_next = true;
            continue;
        }
        if uppercase_next {
            result.extend(character.to_uppercase());
            uppercase_next = false;
        } else {
            result.push(character);
        }
    }
    result
}

pub fn snake_case(value: &str) -> String {
    let characters: Vec<char> = value.chars().collect();
    let mut result = String::with_capacity(value.len() + 4);
    for (index, character) in characters.iter().enumerate() {
        if matches!(character, '-' | ' ') {
            result.push('_');
            continue;
        }
        if character.is_uppercase() && index > 0 {
            let previous = characters[index - 1];
            let next_is_lowercase = characters
                .get(index + 1)
                .is_some_and(|next| next.is_lowercase());
            if previous.is_lowercase()
                || previous.is_ascii_digit()
                || (previous.is_uppercase() && next_is_lowercase)
            {
                result.push('_');
            }
        }
        result.extend(character.to_lowercase());
    }
    result
}

fn method_name(value: &str) -> String {
    escape_identifier(snake_case(value))
}

fn field_name(value: &str) -> String {
    escape_identifier(snake_case(value))
}

fn escape_identifier(value: String) -> String {
    const RESERVED: [&str; 4] = ["self", "Self", "super", "crate"];
    const KEYWORDS: [&str; 48] = [
        "abstract", "as", "async", "await", "become", "box", "break", "const", "continue", "do",
        "dyn", "else", "enum", "extern", "false", "final", "fn", "for", "gen", "if", "impl", "in",
        "let", "loop", "macro", "match", "mod", "move", "mut", "override", "priv", "pub", "ref",
        "return", "static", "struct", "trait", "true", "try", "type", "typeof", "unsafe",
        "unsized", "use", "virtual", "where", "while", "yield",
    ];
    if RESERVED.contains(&value.as_str()) {
        return format!("{value}_");
    }
    if KEYWORDS.contains(&value.as_str()) {
        return format!("r#{value}");
    }
    value
}

fn rustfmt(source: &str) -> Result<String, String> {
    let mut child = Command::new(std::env::var("RUSTFMT").unwrap_or_else(|_| "rustfmt".to_owned()))
        .args(["--edition", "2024", "--emit", "stdout"])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .map_err(|error| format!("start rustfmt: {error}"))?;
    child
        .stdin
        .take()
        .expect("rustfmt stdin is piped")
        .write_all(source.as_bytes())
        .map_err(|error| format!("write to rustfmt: {error}"))?;
    let output = child
        .wait_with_output()
        .map_err(|error| format!("run rustfmt: {error}"))?;
    if !output.status.success() {
        return Err(String::from_utf8_lossy(&output.stderr).into_owned());
    }
    String::from_utf8(output.stdout).map_err(|error| format!("rustfmt output: {error}"))
}
